enableScripts: false

httpTimeout: 10000

nodeLinker: pnp

packageExtensions:
  "vite@*":
    dependencies:
      "supports-color": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-typescript": "*"

pnpFallbackMode: dependencies-only

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.5.1.cjs

supportedArchitectures:
  libc:
    - current
    - glibc
    - musl

  os:
    - current
    - darwin
    - linux
    - win32

  cpu:
    - current
    - x64
    - arm64
    - ia32

